fragment PostsParts on Posts {
  title
  body
}

fragment PagesParts on Pages {
  seo_data {
    __typename
    meta_title
    meta_description
    meta_canonical
  }
  hero {
    __typename
    hero_heading
    hero_description
    hero_button_text
  }
}
