fragment PageParts on Page {
  seo_data {
    __typename
    meta_title
    meta_description
    meta_canonical
  }
  hero {
    __typename
    hero_heading
    hero_description
    hero_button_text
    hero_image
    hero_image_alt
  }
  blocks {
    __typename
    ... on PageBlocksCall_to_action {
      heading
      button_text
    }
    ... on PageBlocksMeet_the_team {
      heading
      description
      team_members {
        __typename
        name
        position
        avatar
      }
    }
    ... on PageBlocksOur_services {
      heading
      services_description
      services {
        __typename
        service_title
        service_description
      }
      services_mission
    }
    ... on PageBlocksPowered_by_data {
      heading
      content
      image
      image_alt
    }
    ... on PageBlocksWho_we_work_with {
      heading
      content
      charities {
        __typename
        charity_name
        charity_logo
      }
    }
    ... on PageBlocksWhy_rg {
      heading
      content
    }
  }
}

fragment LegalParts on Legal {
  seo_data {
    __typename
    meta_title
    meta_description
    meta_canonical
  }
  hero {
    __typename
    hero_heading
    hero_description
  }
  body
}
