query getHomepageDocument($relativePath: String!) {
  getHomepageDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...HomepageParts
    }
  }
}

query getHomepageList {
  getHomepageList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...HomepageParts
        }
      }
    }
  }
}

query getPrivacy_policyDocument($relativePath: String!) {
  getPrivacy_policyDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...Privacy_policyParts
    }
  }
}

query getPrivacy_policyList {
  getPrivacy_policyList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...Privacy_policyParts
        }
      }
    }
  }
}
