query getHomepageDocument($relativePath: String!) {
  getHomepageDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...HomepageParts
    }
  }
}

query getHomepageList {
  getHomepageList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...HomepageParts
        }
      }
    }
  }
}

query getPrivacyDocument($relativePath: String!) {
  getPrivacyDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...PrivacyParts
    }
  }
}

query getPrivacyList {
  getPrivacyList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...PrivacyParts
        }
      }
    }
  }
}
